# This is the configuration file for the fast_cpp_server application.

default_app_name=fast_cpp_server
default_config_dir=/opt/fast_cpp_server/config
default_swagger_res_dir=/usr/share/fast_cpp_server/swagger-res/res
default_logger_dir=/var/fast_cpp_server/logs/
default_temp_dir=/tmp/fast_cpp_server/

app_name=fast_cpp_server
config_dir=__CONFIG_DIR__
swagger_res_dir=__SWAGGER_RES_DIR__
logger_dir=__LOGGER_DIR__
temp_dir=__TEMP_DIR__
# If console_output is set to true, the application will output logs to the console.
# This is useful for debugging purposes, but it may not be suitable for production environments.
console_output=true