# cmake/utils.cmake

function(pretty_print_list title list_var)
    string(ASCII 27 Esc)
    set(ColorGreen "${Esc}[32m")
    set(ColorCyan  "${Esc}[36m")
    set(ColorReset "${Esc}[0m")

    message(STATUS "${ColorCyan}${title}:${ColorReset}")
    set(list_content "${${list_var}}")

    set(max_len 0)
    foreach(item ${list_content})
        string(LENGTH "${item}" len)
        if(len GREATER max_len)
            set(max_len ${len})
        endif()
    endforeach()

    foreach(item ${list_content})
        string(LENGTH "${item}" len)
        math(EXPR padding "${max_len} - ${len}")
        string(REPEAT " " ${padding} spaces)
        message(STATUS "${ColorGreen}item:${ColorReset} ${item}${spaces}")
    endforeach()
endfunction()

function(print_colored_message MESSAGE_STRING)
    set(options BOLD)
    set(oneValueArgs COLOR)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "${options}" "${oneValueArgs}" "")

    string(ASCII 27 Esc)
    set(color_reset "${Esc}[0m")
    set(color_bold "${Esc}[1m")
    set(color_red "${Esc}[31m")
    set(color_green "${Esc}[32m")
    set(color_yellow "${Esc}[33m")
    set(color_blue "${Esc}[34m")
    set(color_magenta "${Esc}[35m")
    set(color_cyan "${Esc}[36m")
    set(color_white "${Esc}[37m")

    set(color_code "")
    if(ARG_COLOR STREQUAL "red")
        set(color_code "${color_red}")
    elseif(ARG_COLOR STREQUAL "green")
        set(color_code "${color_green}")
    elseif(ARG_COLOR STREQUAL "yellow")
        set(color_code "${color_yellow}")
    elseif(ARG_COLOR STREQUAL "blue")
        set(color_code "${color_blue}")
    elseif(ARG_COLOR STREQUAL "magenta")
        set(color_code "${color_magenta}")
    elseif(ARG_COLOR STREQUAL "cyan")
        set(color_code "${color_cyan}")
    elseif(ARG_COLOR STREQUAL "white")
        set(color_code "${color_white}")
    endif()

    if(ARG_BOLD)
        set(color_code "${color_bold}${color_code}")
    endif()

    message("${color_code}${MESSAGE_STRING}${color_reset}")
endfunction()